name: Semantic Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: "vscode-extension/package-lock.json"

      - name: Install Dependencies
        run: npm install
        working-directory: vscode-extension

      - name: Install VSCE
        run: npm install -g vsce

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: vscode-extension

      # - name: Publish extension
      #   run: npx vcse package && npx vcse publish
      #   env:
      #    VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      #   working-directory: vscode-extension
